### ISSUE TITLE
the tags are python while the game is written in c

### ISSUE THREAD

**Issue by jeffparla** [boneill02/awol#1]
# please fix this or i will walk over to your room and beat you up
im serious

**Comment by jeffparla** [comment]
![image](https://user-images.githubusercontent.com/90476759/204386335-3f970b7b-b6fc-488e-aac4-1a8c88a4f239.png)

**Comment by bmoneill** [comment]
ok fixed my b

**Comment by jeffparla** [comment]
do better next time
